// @flow
import type { TONLocalization } from './TONLocalizedTypes';

const ko: TONLocalization = {
    FreeTONLink: {
        linkText: 'Free TON Community',
        link: 'https://freeton.org',
    },
    FreeTONLinkShort: {
        linkText: 'Free TON',
        link: 'https://freeton.org',
    },

    Contests: {
        JoinRequestSent: 'Your request has been sent.',
        SignAndVote: '서명하고 투표하기',
        Vote: 'Vote',
        SomethingWentWrong: 'Something went wrong.',
        VoteFailed: 'Failed to record your vote.',
        VoteHasCast: 'Your vote has been cast.',
        ProposalNew: 'New Contest',
        MakeProposal: '제안서 만들기',
        ToDiscuss: '토론하러 가기',
        AddSubmission: '제출하기',
        AttachPDFText: '제안서 PDF 파일 첨부',
        Submit: '제출하기',
        DiscussionLink: '토론 링크',
        ProposalWalletAddress: '제안 주소',
        ProposalJudgeAddress: '제안서 심사 주소',
        MessageID: 'Proposal acceptance ID',
        ContestAddress: 'Contest address',
        Contest: '컨테스트',
        Contests: '컨테스트',
        Proposals: '제안서',
        GlobalProposals: '글로벌 제안서',
        FreetonWalletAddress: '프리톤 지갑 주소',
        TonsurfAddressOptional: '톤 서프 주소 (옵션)',
        AddressToContactYou: '필요시 심사위원들이 연락하기 위한 주소',
        SubmissionLink: '해당 컨테스트 포럼 링크',
        ProposalKey: '제안 키',
        Create: '만들기',
        Review: '검토 중',
        Created: '작성',
        CastYourVote: '투표하기',
        Status: '현황',
        Description: '내용',
        Discussion: '토론',
        DiscussContest: '컨테스트 논의하기',
        Proposal: '제안서',
        Submission: 'Submission',
        MasterPassword: '마스터 비밀번호 (시드키)',
        NoProposalKey: 'No key?',
        ProposalTitle: '제목',
        ProposalsListTitle: 'Proposals and Contests',

        KoreaSubgovernance: '한국 서브 거버넌스',
        FreetonGovernance: 'Free TON Governance',
        WikiSubgovernance: 'Wiki Subgovernance',
        DefiSubgovernance: 'DeFi Subgovernance',
        AmbassadorSubgovernance: 'Ambassador Subgovernance',
        SmmSubgovernance: 'SMM Subgovernance',
        DgoSubgovernance: 'DGO Subgovernance',
        EsportsSubgovernance: 'eSports Subgovernance',
        DevexSubgovernance: 'DevEx Subgovernance',
        SupportSubgovernance: 'A&S Subgovernance',
        WdSubgovernance: 'W&D Subgovernance',
        FreetonWiki: 'Wiki Subgovernance',
        FreetonKorea: 'Free TON Korea Governance',
        FreetonDefi: 'Free TON DeFi Governance',
        FreetonAmbassador: 'Free TON Ambassador Governance',
        FreetonSmm: 'Free TON SMM Governance',
        FreetonDgo: 'Free TON DGO Governance',
        FreetonEsports: 'Free TON eSports Governance',
        FreetonDevex: 'Free TON Dev Experience Governance',
        FreetonSupport: 'Free TON Analytics & Support Governance',
        FreetonWd: 'Free TON Web & Design Governance',
        TONCommunity: 'Free TON Community',
    },
};

export default ko;
