// @flow
import type { TONLocalization } from './TONLocalizedTypes';

const ru: TONLocalization = {
    FreeTONLink: {
        linkText: 'Free TON Community',
        link: 'https://freeton.org',
    },
    FreeTONLinkShort: {
        linkText: 'Free TON',
        link: 'https://freeton.org',
    },

    Contests: {
        JoinRequestSent: 'Your request has been sent.',
        SignAndVote: 'Sign and Vote',
        Vote: 'Vote',
        SomethingWentWrong: 'Something went wrong.',
        VoteFailed: 'Failed to record your vote.',
        VoteHasCast: 'Your vote has been cast.',
        ProposalNew: 'New Contest',
        MakeProposal: 'Create Proposal',
        ToDiscuss: 'To discuss',
        AddSubmission: 'Add submission',
        AttachPDFText: 'Attach description .PDF file',
        Submit: 'Submit',
        DiscussionLink: 'Discussion link',
        ProposalWalletAddress: 'Proposal address',
        ProposalJudgeAddress: 'Proposal jury address',
        MessageID: 'Proposal acceptance ID',
        ContestAddress: 'Contest address',
        Contest: 'Contest',
        Contests: 'Contests',
        Proposals: 'Proposals',
        GlobalProposals: 'Global Proposals',
        FreetonWalletAddress: 'Free TON wallet address',
        TonsurfAddressOptional: 'TON Surf address (optional)',
        AddressToContactYou: 'Address for jurors to contact you',
        SubmissionLink: 'Submission link',
        ProposalKey: 'Proposal key',
        Create: 'Create',
        Review: 'Review',
        Created: 'Created',
        CastYourVote: 'Cast your vote',
        Status: 'Status',
        Description: 'Description',
        Discussion: 'Discussion',
        DiscussContest: 'Discuss contest',
        Proposal: 'Proposal',
        Submission: 'Submission',
        MasterPassword: 'Master password (seed phrase)',
        NoProposalKey: 'No key?',
        ProposalTitle: 'Title',
        ProposalsListTitle: 'Proposals and Contests',

        KoreaSubgovernance: 'Korean Subgovernance',
        FreetonGovernance: 'Free TON Governance',
        WikiSubgovernance: 'Wiki Subgovernance',
        DefiSubgovernance: 'DeFi Subgovernance',
        AmbassadorSubgovernance: 'Ambassador Subgovernance',
        SmmSubgovernance: 'SMM Subgovernance',
        DgoSubgovernance: 'DGO Subgovernance',
        EsportsSubgovernance: 'eSports Subgovernance',
        DevexSubgovernance: 'DevEx Subgovernance',
        SupportSubgovernance: 'A&S Subgovernance',
        WdSubgovernance: 'W&D Subgovernance',
        FreetonWiki: 'Wiki Subgovernance',
        FreetonKorea: 'Free TON Korea Governance',
        FreetonDefi: 'Free TON DeFi Governance',
        FreetonAmbassador: 'Free TON Ambassador Governance',
        FreetonSmm: 'Free TON SMM Governance',
        FreetonDgo: 'Free TON DGO Governance',
        FreetonEsports: 'Free TON eSports Governance',
        FreetonDevex: 'Free TON Dev Experience Governance',
        FreetonSupport: 'Free TON Analytics & Support Governance',
        FreetonWd: 'Free TON Web & Design Governance',
        TONCommunity: 'Free TON Community',
    },
};

export default ru;
