module.exports = {
    presets: [
        'module:metro-react-native-babel-preset',
        '@babel/preset-flow',
    ],
    plugins: [
        ['@babel/plugin-proposal-numeric-separator'],
        ['@babel/plugin-proposal-decorators', { legacy: true }],
        [
            'rewrite-require',
            {
                aliases: {
                    constants: 'constants-browserify',
                    crypto: 'react-native-crypto',
                    dns: 'node-libs-browser/mock/dns',
                    domain: 'domain-browser',
                    fs: 'node-libs-browser/mock/empty',
                    http: 'stream-http',
                    https: 'https-browserify',
                    net: 'react-native-tcp',
                    os: 'os-browserify/browser',
                    path: 'path-browserify',
                    pbkdf2: 'react-native-pbkdf2-shim',
                    querystring: 'querystring-es3',
                    stream: 'stream-browserify',
                    _stream_duplex: 'readable-stream/duplex',
                    _stream_passthrough: 'readable-stream/passthrough',
                    _stream_readable: 'readable-stream/readable',
                    _stream_transform: 'readable-stream/transform',
                    _stream_writable: 'readable-stream/writable',
                    sys: 'util',
                    timers: 'timers-browserify',
                    tls: 'node-libs-browser/mock/tls',
                    tty: 'tty-browserify',
                    vm: 'vm-browserify',
                    zlib: 'browserify-zlib',
                },
                throwForNonStringLiteral: true,
            },
        ],
        [
            'module-resolver', {
                root: ['./src/'],
                alias: {
                    '@uikit/assets': './src/services/UIKit/packages/assets',
                    '@uikit/core': './src/services/UIKit/packages/core/src',
                    '@uikit/components': './src/services/UIKit/packages/components/src',
                    '@uikit/chat': './src/services/UIKit/packages/chat/src',
                    '@uikit/navigation': './src/services/UIKit/packages/navigation/src',
                    '@uikit/legacy': './src/services/UIKit/packages/legacy/src',
                    '#UIKit': './src/services/UIKit',
                    '#assets': './src/assets',
                    '#services': './src/services',
                    '#helpers': './src/helpers',
                    '#components': './src/components',
                    '#navigation': './src/navigation',
                    '#controllers': './src/controllers',
                    '#TONLocalized': './src/TONLocalized',
                    '#TONUtility': './src/helpers/TONUtility',
                    '#TONWalletSetup': './src/helpers/TONWalletSetup',
                    '#TONWallet': './src/helpers/TONWallet',
                    '#TONContracts': './src/helpers/TONContracts',
                },
                extensions: ['.js'],
            },
        ],
    ],
};
