// Auth actions
const IS_LOGGED_IN = 'IS_LOGGED_IN';
const SHOW_CONTROLLER = 'SHOW_CONTROLLER';
const SET_BACKGROUND_PRESET = 'SET_BACKGROUND_PRESET';
const SET_SCREEN_WIDTH = 'SET_SCREEN_WIDTH';
const SET_MOBILE = 'SET_MOBILE';
const NAVIGATION_MENU_CONTROLLER = 'NAVIGATION_MENU_CONTROLLER';

export {
    IS_LOGGED_IN,
    SHOW_CONTROLLER,
    SET_BACKGROUND_PRESET,
    SET_SCREEN_WIDTH,
    SET_MOBILE,
    NAVIGATION_MENU_CONTROLLER,
};
